package gamelog

const (
        UNKNOWN = iota
        ALISTAR
        ANNIE
        ASHE
        FIDDLESTICKS
        JAX
        KAYLE
        MASTER_YI
        MORGANA
        NUNU
        RYZE
        SION
        SIVIR
        SORAKA
        TEEMO
        TRISTANA
        TWISTED_FATE
        WARWICK
        SINGED
        ZILEAN
        EVELYN
        TWITCH
        TRYNDAMERE
        KARTHUS
        CHOGATH
        AMUMU
        ANIVIA
        RAMMUS
        VEIGAR
        KASSADIN
        GANGPLANK
        TARIC
        MALPHITE
        JANNA
        BLITZCRANK
        DR_MUNDO
        KATARINA
        CORKI
        NASUS
        HEIMERDINGER
        SHACO
        UDYR
        NIDALEE
        POPPY
        GRAGAS
        PANTHEON
        MORDEKAISER
        EZREAL
        SHEN
        KENNEN
        GAREN
        AKALI
        MALZAHAR
        OLAF
        KOGMAW
        XIN_ZHAO
        VLADMIR
        GALIO
        URGOT
        MISS_FORTUNE
        SONA
        SWAIN
        LUX
        LEBLANC
        IRELIA
        TRUNDLE
        CASSIOPEIA
        CAITLYN
        RENEKTON
        KARMA
        MAOKAI
        JARVAN_IV
        NOCTURNE
        LEE_SIN
        BRAND
        RUMBLE
        VAYNE
        ORIANNA
        YORICK
        LEONA
        WUKONG
        SKARNER
        TALON
        RIVEN
        XERATH
        GRAVES
        SHYVANA
        FIZZ
        VOLIBEAR
        AHRI
        VIKTOR
        SEJUANI
        ZIGGS
        NAUTILUS
        FIORA
        LULU
        HECARIM
        VARUS
        DARIUS
        DRAVEN
        JAYCE
        ZYRA
        DIANA
        RENGAR
        SYNDRA
        KHAZIX
        ELISE
        ZED
        NAMI
        VI
        THRESH
        QUINN
        ZAC
        LISSANDRA
        AATROX
        LUCIAN
        JINX
        YASUO
        VELKOZ
        BRAUM
)
